name: POC Cloudflare Purge Cache

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true

jobs:
  purge-cache:
    name: Purge Cache
    uses: ./.github/workflows/purge-cache2.yml
    with:
      environment: dev
    secrets:
      TEST_KEY: ${{ secrets.TEST_KEY }}
