name: POC Cloudflare Purge Cache

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true

jobs:
  cloudflare-purge-cache:
    name: Cloudflare Purge Cache
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      api_key: ${{ steps.deploy.outputs.api_key }}
    steps:
      - id: deploy
        name: Deploy
        shell: bash
        run: |
          echo "deploying ..."
          echo "API_KEY=${{ secrets.API_KEY }}"
          echo "api_key=${{ secrets.API_KEY }}" >> "$GITHUB_OUTPUT"

  purge-cache:
    name: Purge Cache
    needs: cloudflare-purge-cache
    uses: ./.github/workflows/purge-cache2.yml
    with:
      environment: dev
    secrets:
      api_key: ${{ needs.cloudflare-purge-cache.outputs.api_key }}
