name: POC Cloudflare Purge Cache

on:
  workflow_dispatch:

jobs:
  cloudflare-purge-cache:
    name: Cloudflare Purge Cache
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      api-key: ${{ steps.deploy.outputs.api-key }}
    steps:
      - id: deploy
        name: Deploy
        shell: bash
        run: |
          echo "deploying ..."
          run: echo "api-key=${{ secrets.api-key }}" >> "$GITHUB_OUTPUT"

  purge-cache:
    name: Purge Cache
    needs: cloudflare-purge-cache
    uses: ./.github/workflows/purge-cache2.yml
    with:
      environment: dev
    secrets:
      api-key: ${{ needs.cloudflare-purge-cache.outputs.api-key }}
