name: Cloudflare Purge Cache

on:
  workflow_dispatch:

jobs:
  test-tag-release:
    name: Cloudflare Purge Cache
    runs-on: ubuntu-latest
    steps:
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: xx
          CLOUDFLARE_TOKEN: xx
