on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      api-key:
        required: true

jobs:
  upload-to-s3-public-bucket:
    name: Upload to s3 ${{ inputs.environment }} public bucket
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Purge cache
        shell: bash
        run: |
          curl --location 'https://dev-cdn.nocnoc-internal.com/cache-purger' \
          --header 'x-api-key: ${{ secrets.api-key }}' \
          --header 'Content-Type: application/json' \
          --data '{
              "pathPrefixList": ["mock/test-api/"]
          }'
