name: Test step output

on:
  workflow_dispatch:

jobs:
  test-step-output:
    name: Test step output
    runs-on: ubuntu-latest
    steps:
      - id: step-1
        name: step 1
        shell: bash
        run: |
          string="release/1.0.0"

          IFS='/'

          read -ra arr <<<"$string"

          length=${#arr[@]}

          version="${arr[$length - 1]}"

          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: step 2
        shell: bash
        run: |
          echo "version=${{ steps.step-1.outputs.version }}"
