name: Test command
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true

jobs:
  upload-to-s3-public-bucket:
    name: Upload to s3 ${{ github.event.inputs.environment }} public bucket
    uses: ./.github/workflows/test-call-command.yml
    with:
      environment: ${{ github.event.inputs.environment }}
