on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  upload-to-s3-public-bucket:
    name: Upload to s3 ${{ inputs.environment }} public bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Rename mobile associated files
        shell: bash
        run: |
          appleAppSiteAssociation=".well-known/${{ inputs.environment }}-apple-app-site-association"

          if [ -f "$appleAppSiteAssociation" ]; then
            mv $appleAppSiteAssociation .well-known/apple-app-site-association
          fi

          assetLinks=".well-known/${{ inputs.environment }}-assetlinks.json"

          if [ -f "$assetLinks" ]; then
            mv $assetLinks .well-known/assetlinks.json
          fi

          ls .well-known
