name: Test if

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: dev
        description: Environment
        type: choice
        options:
          - dev
          - qa
          - preprod
          - prod

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    name: Clear cache ${{ inputs.environment }} environment
    steps:
      - name: Purge cache
        shell: bash
        run: |
          version=""
          if [[ "${{inputs.environment}}" == "dev" ]]; then
            version="development"
          elif [[ "${{inputs.environment}}" == "qa" ]]; then
            version="qa"
          elif [[ "${{inputs.environment}}" == "preprod" ]]; then
            version="preproduction"
          elif [[ "${{inputs.environment}}" == "prod" ]]; then
            version="production"
          fi

          curl --location --request PATCH 'https://dev-cdn.nocnoc-internal.com/env-patcher' \
            --header 'x-api-key: b390f94f46c404e1f4bae34ee9ab02b1' \
            --header 'Content-Type: application/json' \
            --data '{
              "workerName": "s3-hosting-buyer-ui-$version",
              "envName": [
                {
                    "key": "APP_OBJECT_PREFIX",
                    "value": "44ee0612f6900e90707ba0a5c5d0eadd6544007a"
                }
              ]
            }'
